### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by VoLuong** [aleksandar-todorovic/awesome-linux#28]
Hi. I have done this : https://github.com/VoLuong/Awesome-Linux-Software .
I found that yours and mine repo have many parts in common :D Do you ever think about merging them? Not neccessarily under one repo, you can replace a lot of things with just 1 link to my repo though ;-?

**Comment by aleksandar-todorovic** [comment]
Hi,

I have no intention of merging the lists. 

However, I will link to your repo in the "related awesome lists" section and, if I get your permission (since the licenses we're using are different), I am going to copy some of the software you have listed in your repo.

Don't have time to do that immediately, so I'm going to leave this issue open and (hopefully) remember to do that later on. If I don't, please ping me here.

**Comment by aleksandar-todorovic** [comment]
Any updates on the permission to copy some of the software descriptions from you?

**Comment by VoLuong** [comment]
Oops I am so sorry. DId not see your comment on Aug 26th.
Yes, you can totally copy the software descriptions from my repo. It's just language, nothing serious :D
